language: shell
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - sourceline: 'ppa:neovim-ppa/unstable'
    packages:
      - neovim

before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" = osx ]]; then
    brew update
    brew install neovim
  fi
script:
  - ./foo
  - ./bar
  - ./baz
  - ./main.zsh
