language: shell
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - sourceline: 'ppa:neovim-ppa/unstable'
    packages:
      - neovim

before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" = osx ]]; then
    brew update
    brew install neovim
  fi
script:
  - ./foo
  - ./bar
  - ./baz
  - ./main.zsh
  - bash -c 'exec -a plain-bash ps -o pid,comm,args $$'
  - zsh -c 'exec -a plain-zsh ps -o pid,comm,args $$'
  - bash -c 'exec -a plain-bash.nvim nvim --cmd "echo nvim_get_proc($$)" --cmd quit'
  - zsh -c 'exec -a plain-zsh.nvim nvim --cmd "echo nvim_get_proc($$)" --cmd quit'
