language: shell
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - sourceline: 'ppa:neovim-ppa/unstable'
    packages:
      - luarocks
      - neovim
      - pandoc
before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" = osx ]]; then
    brew update
    brew install neovim pandoc lua
  fi
  luarocks --local install busted
install: make install PREFIX=$HOME/.local
script:
      - make test BUSTED=$HOME/.luarocks/bin/busted || true
      - test/fixtures/bin/man ./nvimpager -c test/fixtures/man.cat -c 'echo &ft' 2>&1 | hexdump -C
      - hexdump -C test/fixtures/man.ansi
      - nvim --version
